#app:
 #   resource: @AppBundle/Controller/
 #   type:     annotation

ibw_jobeet:
    resource: "@IbwJobeetBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: |en|fr
    defaults: { _locale: en}

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin